[Iter13] feat:Add retries
benderr/metrics pull request #13
Opened 2023-11-13 07:07 UTC by benderr

2023-11-14 15:11 UTC, capsulated requested changes
Всё в принципе супер, но создание sql подключения, да и вообще switch с конструкторами хранилок нужно убрать в пакет хранилки. Описал в комментариях

2023-11-14 15:11 UTC, capsulated commented on cmd/server/main.go
> +	switch {
❌ Это уже пора "убирать" в пакет `storage`. sql.Open точно не место в `cmd`. Соответсвенно, удобно описать интерфейс для хранилки, и вызывать конструктор, в зависимости от конфига. Функцию, у которой на входе конфиг, в теле вызывается соотвествующий конструктор, а выходой параметр описан интерфейсом - является абстракной фабрикой. Её лучше также поместить в пакет хранилки.

2023-11-14 15:11 UTC, capsulated commented on cmd/agent/main.go
> +	l, lerr := zap.NewDevelopment()
Можно вынести в отдельный пакет, но пока некритично (пока инициализация небольшая и нет интерфейсов)

2023-11-14 15:11 UTC, capsulated commented on internal/handlers/dbretry.go
> +func CanRetry(attempt int, err error) bool {
Интересно 🤔😄

2023-11-14 15:11 UTC, capsulated commented on internal/retry/retry_test.txt
> +// package retry_test
Что-то тут лишнее в реп попало)

2023-11-14 15:11 UTC, capsulated commented on internal/handlers/handlers.go
> +		return a.metricRepo.Get(ctx, metric.ID)
Контекст не совсем правильно используется, но к этому мы ещё придём в следующих спринтах. Так как контекстов ещё не проходили

2023-11-15 05:47 UTC, benderr commented on internal/handlers/dbretry.go
> +func CanRetry(attempt int, err error) bool {
В общем я это удалил) Сделал на уровне dbStorage композицию, можно использовать репу в обычном режиме, может вызвать другой конструктор с реализацией ретраев NewWithRetry

2023-11-15 05:48 UTC, benderr commented on cmd/server/main.go
> +	switch {
Вынес в storage

2023-11-15 05:48 UTC, benderr commented on internal/retry/retry_test.txt
> +// package retry_test
Удалил

2023-11-15 05:48 UTC, benderr commented on internal/handlers/handlers.go
> +		return a.metricRepo.Get(ctx, metric.ID)
как смог)

2023-11-15 08:38 UTC, benderr commented on cmd/agent/main.go
> +	l, lerr := zap.NewDevelopment()
вынес

2023-11-15 16:21 UTC, capsulated approved these changes
Всё круто! 🔥

2023-11-15 18:40 UTC, merged