[Iter18] feat: add docs
benderr/metrics pull request #19
Opened 2024-01-29 15:33 UTC by benderr

2024-01-29 17:50 UTC, benderr commented on internal/server/app/app.go
> +	chiRouter.Route("/debug/pprof", func(r chi.Router) {
Регистрация ручек pprof так как используется не стандартный mux

2024-01-29 17:50 UTC, benderr commented on internal/server/handlers/handlers.go
> +// Information is received from response.Body.
Добавил сваггер для пары ручек в качестве примера

2024-01-29 17:52 UTC, benderr commented on internal/server/repository/inmemory/storage_fast.go
> +package inmemory
Добавил еще одну реализацию для in-memory репозитория, чтобы сравнить на бенчмарках релизацию со слайсами и с мапой

2024-01-29 17:55 UTC, benderr commented on internal/server/repository/inmemory/storage_test.go
> +func BenchmarkGet(b *testing.B) {
![image](https://github.com/benderr/metrics/assets/4123546/cdf989c6-1d2f-4aac-ba29-a763a05b2400)
Собственно для наших потребностей больше подходит хранилище в виде мапы а не слайса, так как приходится часто обращаться по ключам (ID) чтобы проапдейтить

Но мы проигрываем в случае когда нужно вернуть весь список, так как мапа всегда рандомно итерируется, его надо будет сортировать, но это можно решить кешированием и в целом в рамках данной задачи не существенно

2024-01-29 17:58 UTC, benderr commented on internal/server/repository/storage/storage.go
> +		repo = inmemory.NewFast()
Собственно после изменения реализации `pprof` показал следующий diff
![image](https://github.com/benderr/metrics/assets/4123546/bca9e93b-19a5-4036-9252-833fe7111989)

2024-01-29 17:59 UTC, benderr commented on swagger/swagger.json
> +{
Решил добавить просто для примера, раз у нас в спринте о них тоже говорилось

2024-01-29 18:03 UTC, benderr commented on internal/server/repository/inmemory/storage_test.go
> +func ExampleKeyValueMetricRepository_BulkUpdate() {
Добавил примеры, но они в `internal` по этому просматривать их можно только через `/?m=all` 
Пруф-скрины
![image](https://github.com/benderr/metrics/assets/4123546/c89d20c4-783c-445a-8531-5bfb32e5706b)
![image](https://github.com/benderr/metrics/assets/4123546/67b54d39-258e-4299-b67a-1f139f08ace6)

2024-02-01 17:40 UTC, capsulated commented on internal/server/handlers/handlers.go
> +// Information is received from response.Body.
Агонь 🔥

2024-02-01 17:42 UTC, capsulated commented on internal/server/repository/inmemory/storage_test.go
> +func ExampleKeyValueMetricRepository_BulkUpdate() {
Вот отлично, но это же явный признак, что хранилку вообще в pkg надо выносить)

2024-02-01 17:50 UTC, capsulated requested changes
Сваггер - шикарен
Профилировщик - всё ок
Импорты и отступы - на месте

Единственное замечание: всё же выделить публичные пакеты в pkg. Stgorage по идее тоже в pkg - но это много переносить, можно компрессор, аунтификатор к примеру

В идеале, в internal только часть логики должна быть, по аналогии с private/public переменными, каждая директория internal - это private пакет. И также, по аналогии, не все переменные у нас внутренние. Всё, что может использоваться в других проектах лучше вынести как независимые пакеты в pkg, а затем и вообще отдельный git репозиторий создать. Это один из видов появления opensource библиотек)))

2024-02-05 20:07 UTC, capsulated commented on internal/server/repository/inmemory/storage_test.go
> +func ExampleKeyValueMetricRepository_BulkUpdate() {
Хотя, если хранилка `pkg`, тогда её методы - это уже отделять надо будет в виде UseCase, а они явно для internal. В любом случае, всё зависит от переиспользования пакета: если планируется его импортировать из пакета в пакет с точно такими же запросами - тогда легко можно перенести в `pkg`. Ну это скорее мысли в слух)))

2024-02-05 20:09 UTC, capsulated approved these changes
Всё супер!

По `internal` рекомендация (для понимания, так же): можно проанализировать инкременты и выпускной gofrtmart. Найти дублирующийся функционал в виде пакетов. Именно эти пакеты - главный претендент для переноса в pkg и его можно импортировать, скажем, в следующем выпускном проекте. Это аналоги public/private для переменных, только в рамках пакета. То есть, всё что в internal - это private пакеты

2024-02-06 05:03 UTC, merged