[Iter20] feat: add linters and params for ldflags
benderr/metrics pull request #20
Opened 2024-02-14 07:31 UTC by benderr

2024-02-17 01:07 UTC, capsulated requested changes
1. Добавить в доку `каждый анализатор и его назначение`. Можно скпопастить из комментариев доков из их сорсов
2. Тесты покрытия показывает `total: (statements)  51.2%`
3. Публичный анализатор только один - acshiicheck? Второй какой нибудь бы

Остальное всё ок.

P.S. Читаю твой код - нейминг 🦾, локальные переменные сокращённые, глобальные, пакеты - без сокращений, хорошая общая структура пакетов и объектов, читать приятно 👍

2024-02-17 08:42 UTC, benderr commented
> 1. Добавить в доку `каждый анализатор и его назначение`. Можно скпопастить из комментариев доков из их сорсов
> 2. Тесты покрытия показывает `total: (statements)  51.2%`
> 3. Публичный анализатор только один - acshiicheck? Второй какой нибудь бы
> 
> Остальное всё ок.
> 
> P.S. Читаю твой код - нейминг 🦾, локальные переменные сокращённые, глобальные, пакеты - без сокращений, хорошая общая структура пакетов и объектов, читать приятно 👍

1. ok
2. ok
3. Публичных два, `asciicheck` и `go-mnd` (magic-number)

2024-02-18 05:31 UTC, benderr commented
Покрытие довел до `total: (statements) 59.6%`

2024-02-19 13:13 UTC, capsulated reviewed
Всё ок 👍

2024-02-19 13:14 UTC, capsulated approved these changes
Всё ок 👍

2024-02-19 18:14 UTC, merged