[Iter23] feat: add gracefull shutdown
benderr/metrics pull request #23
Opened 2024-02-25 15:02 UTC by benderr

2024-02-26 22:10 UTC, capsulated requested changes
1. В агенте ты создаёшь контекст с `cmd`, а в сервере в `app`. Нужно бы единообразие.
2. В агенте, мне кажется, лучше разделить select: для report одну рутину, а для прослушивания сигналов системы - отдельную. Я обычно последнюю в конец app перемещаю, так как ясно, что тут завершение программы
3. Какой-то gracefully sthotdown не достаточно gracefully): в агенте вроде ок, отправляются метрики, а в сервере просто вырубается (shotdown) сервер, а вот ожидания плавного завершения repository не вижу, я что-то пропустил?
4. В `cmd/server/main.go` имена переменных такие же, как имена импортируемых пакетов, имена переменных сократить, так они по факту локальные (зря я тебя похвалил в прошлый раз)))
5. Какие-то подозрительно одинаковые логгеры у клиента и сервера, может сделать их единым пакетом? И вообще, проверить, не дублируется ли функционал в `internal/agent` и `internal/server`. И объединить, если дублируется

И менее критичные замечания:
- Много возвращаемых error не обрабатываются, их надо бы вывести в логи/на экран
- Интерфейсы с префиксом `I` заменить бы на `er` (`IReport` на `Reporter`)

Обсудим всё это ещё на 1-1 и после закроем PR

2024-02-26 22:10 UTC, capsulated commented on configs/server.json
> +    "database_dsn": "",
А что connection string пустой?

2024-02-26 22:10 UTC, capsulated commented on cmd/agent/main.go
> +	ctxStop, stop := signal.NotifyContext(ctx, syscall.SIGINT, syscall.SIGQUIT, syscall.SIGTERM)
В агенте ты создаёшь контекст с `cmd`, а в сервере в `app`

2024-02-27 05:01 UTC, benderr commented on configs/server.json
> +    "database_dsn": "",
так этот конфиг просто для тестов) зачем мне там палить свой постгре с паролями

2024-02-27 05:02 UTC, benderr commented on cmd/agent/main.go
> +	ctxStop, stop := signal.NotifyContext(ctx, syscall.SIGINT, syscall.SIGQUIT, syscall.SIGTERM)
перенес все в internal

2024-02-27 05:10 UTC, benderr commented
1. Перенес
2. Тут не согласен, здесь же select сделан как элемент синхронизации, нельзя одновремено в одной горутине менять репорт (собирать новые метрики рантайма) и одновременно в другой горутине отправлять их на сервер. И тут же обрабатывается ctx.Done() для gracefull, то есть если мы в select-e зашли в какую-то операцию, то след итерация селекта (с завершением ctx.Done()) не выполнится пока не отработает либо send либо update
3. Тут все ок, там при вызове shutdown есть еще канал, который ждет когда закроются все соединения, то есть он ждет когда отработают все хендлеры и коннекты закроются, внутри метода shutdown даже есть коммент `
// Shutdown gracefully shuts down the server without interrupting any
// active connections. Shutdown works by first closing all open
// listeners, then closing all idle connections, and then waiting
// indefinitely for connections to return to idle and then shut down.`
 Я это проверял так, ставил time.Sleep в хендлере на 5 секунд, и программа завершается не сразу при ctrl+C а только по истечении этих самых 5 секунд, пока выполнялся хендлер

4. поправил
5. Перенес в pkg, там по сути используется сторонний логер

По поводу приписки I в интерфейсах, это тоже каноничное название I + существительное

2024-02-28 04:35 UTC, merged