[Iter5] feat: Add env params
benderr/metrics pull request #5
Opened 2023-10-04 04:07 UTC by benderr

2023-10-05 18:42 UTC, capsulated requested changes
Оставил комментарии. 

Критичные комментарии отмечены символом ❌ и их обязательно нужно исправить

2023-10-05 18:42 UTC, capsulated commented on cmd/agent/flags.go
> +package main
Лучше бы в отдельный пакет чтение конфигов вынести... Но думаю в следующих спринтах естественным образом к этому придём

2023-10-05 18:42 UTC, capsulated commented on cmd/handlers/handlers.go
> +func MakeRouter(store storage.MemoryRepository) *chi.Mux {
По неймингу:  MakeRouter - это конструктор, [в го принято](https://go.dev/doc/effective_go#composite_literals) конструкторы именовать с префиксом `New` (пример с chi ниже, также `chi.NewRouter()`).

2023-10-05 18:42 UTC, capsulated commented on cmd/storage/storage.go
> +package storage
❌ `storage` из `cmd` необходимо убрать. Например, в `internal` в нашем случае

2023-10-05 18:42 UTC, capsulated commented on cmd/agent/main.go
> +func main() {
В `cmd` должно быть только конфигурирование и запуск нашей логики - воркеров

2023-10-05 18:42 UTC, capsulated commented on cmd/handlers/handlers.go
> +package handlers
❌ `package handlers` перенести из `cmd` в `internal`

2023-10-05 18:42 UTC, capsulated commented on cmd/handlers/handlers.go
> +	r.Get("/", GetMetricListHandler(store))
Передавать зависимости в параметрах функций - bad practice. Лучше создать структуру для хендлеров (по примеру storage) и в конструктор один раз передать зависимость. Иначе, для каждого хендлера надо будет передавать зависимость. А если хендлеров будет много?

2023-10-05 18:42 UTC, capsulated commented on cmd/metrics/handlers.go
> +func updateReport(m *Metrics) {
Тоже, по-хорошему, "упаковать" бы в структуру

2023-10-05 18:42 UTC, capsulated commented on cmd/metrics/handlers.go
> +func StartAgent(poolInterval int, reportInterval int, server string) <-chan struct{} {
И тут, в идеале, структура и её функция запуска: `agent.Start` или `agent.Run`, после [конструктора](https://go.dev/doc/effective_go#composite_literals) вида: `func NewAgent(...)`

2023-10-05 18:42 UTC, capsulated commented on cmd/metrics/metrics.go
> +package metrics
❌ Тоже, убрать из `cmd`

2023-10-05 18:42 UTC, capsulated commented on cmd/server/flags.go
> +func init() {
Желательно, отдельным пакетом `config`

2023-10-05 18:42 UTC, capsulated commented on cmd/storage/storage.go
> +type MemoryRepository interface {
Обычно, если интерфейс не используется, то и не нужен. Но он нам понадобится далее =) Но "на будущее" оставлять код плохо - `not clean`

2023-10-05 18:42 UTC, capsulated commented on cmd/validate/validate.go
> +package validate
❌ перенести из `cmd`

2023-10-05 18:42 UTC, capsulated commented on temp
Удалить бы, лишний

2023-10-06 05:15 UTC, benderr commented on cmd/storage/storage.go
> +type MemoryRepository interface {
используется же, в хендлерах идет работа через интерфейс, и в тестах написан мок-сторедж на этот интерфейс

2023-10-07 06:23 UTC, benderr commented on cmd/agent/flags.go
> +package main
done

2023-10-07 06:24 UTC, benderr commented on cmd/handlers/handlers.go
> +func MakeRouter(store storage.MemoryRepository) *chi.Mux {
сделал через New

2023-10-07 06:24 UTC, benderr commented on cmd/storage/storage.go
> +package storage
done

2023-10-07 06:24 UTC, benderr commented on cmd/agent/main.go
> +func main() {
done

2023-10-07 06:24 UTC, benderr commented on cmd/handlers/handlers.go
> +package handlers
done

2023-10-07 06:25 UTC, benderr commented on cmd/handlers/handlers.go
> +	r.Get("/", GetMetricListHandler(store))
вот тут честно не понял как нужно сделать, если есть пример, то буду благодарен, вообще наверно это делается через контексты, но до них я пока еще не дошел

2023-10-07 06:26 UTC, benderr commented on cmd/metrics/handlers.go
> +func updateReport(m *Metrics) {
сделал методом

2023-10-07 06:26 UTC, benderr commented on cmd/metrics/handlers.go
> +func StartAgent(poolInterval int, reportInterval int, server string) <-chan struct{} {
переделал в структуру

2023-10-07 06:26 UTC, benderr commented on cmd/metrics/metrics.go
> +package metrics
done

2023-10-07 06:26 UTC, benderr commented on cmd/server/flags.go
> +func init() {
done

2023-10-07 06:26 UTC, benderr commented on cmd/validate/validate.go
> +package validate
done

2023-10-07 06:26 UTC, benderr commented on temp
done

2023-10-08 19:18 UTC, capsulated commented on cmd/handlers/handlers.go
> +	r.Get("/", GetMetricListHandler(store))
```go
 // В данной реализации мы передаём зависимость storage
 // только в одном месте - в конструкторе, и в каждый хендлер в параметрах уже 
 // не нужно его передавать каждый раз
 func NewHandlers(s storage) *handlers { ... }
 h := handlers.NewHandlers(...)
 
 func NewRouter(h handlers) {
    r := chi.NewRouter()

    r.Get("/", h.GetMetric)
    ...
 }
 ```

2023-10-08 19:27 UTC, capsulated approved these changes
Добавил пару комментариев, уже в следующем спринте легко можно поправить.

И насчёт отдельной структуры хендлеров обязательно посмотри: https://github.com/benderr/metrics/pull/5#discussion_r1349764000

2023-10-08 19:27 UTC, capsulated commented on internal/metrics/handlers.go
> +func sendMetrics(m *Metrics, client *resty.Client) {
Эту функцию тоже можно сделать методом агента

2023-10-08 19:27 UTC, capsulated commented on internal/metrics/handlers.go
> +func (agent *Agent) Run() <-chan struct{} {
Принято первую букву использовать - это для того, чтобы понимать, что объект  `agent` это указатель на текущую структуру (аналог `this` из других ЯП)

```
func (a *Agent) ...
```

2023-10-08 19:27 UTC, capsulated commented on internal/metrics/handlers.go
> +				sendMetrics(report, client)
И тут, соответсвенно, получится:
```
a.sendMetrics(report, client)
```

2023-10-09 04:25 UTC, benderr commented on cmd/handlers/handlers.go
> +	r.Get("/", GetMetricListHandler(store))
вроде понял, спасибо. Переделаю

2023-10-09 04:25 UTC, benderr commented on internal/metrics/handlers.go
> +func sendMetrics(m *Metrics, client *resty.Client) {
done

2023-10-09 04:25 UTC, benderr commented on internal/metrics/handlers.go
> +func (agent *Agent) Run() <-chan struct{} {
done

2023-10-09 04:25 UTC, benderr commented on internal/metrics/handlers.go
> +				sendMetrics(report, client)
done

2023-10-17 06:06 UTC, merged