[Iter9] feat: add file storage
benderr/metrics pull request #9
Opened 2023-10-30 19:51 UTC by benderr

2023-10-31 13:25 UTC, capsulated requested changes
Пару критичных замечаний написал. Но всё остальное, в принципе, очень даже классно

2023-10-31 13:25 UTC, capsulated commented on cmd/config/serverconfig/main.go
>  import (
⚠️ Конфиг стал полноценным объектом и оставлять его в `cmd` не совсем правильно, так как тут логики много. Если бы был простой парсинг флаги - то ок. А сейчас лучше бы его в internal перенести, к тому же конфиг стал общим для сервера и агента

2023-10-31 13:25 UTC, capsulated commented on internal/validate/validate.go
> +func ParseCounter(memType, name, value string) (*storage.Metrics, error) {
По факту, эти функции используются только в хендлерах. Предлагаю перенести просто этот файл в пакет хендлеров

2023-10-31 13:25 UTC, capsulated commented on cmd/server/main.go
> +func getReaderFunc(filePath string) func() (io.ReadCloser, error) {
❌ Ридер файла с уровня `cmd` нужно убрать в пакет

2023-10-31 13:25 UTC, capsulated commented on cmd/server/main.go
> +func getWriterFunc(filePath string) func() (io.WriteCloser, error) {
❌ И writer также  убрать в пакет

2023-10-31 13:25 UTC, capsulated commented on cmd/server/main.go
> +type metricDumpRepository struct {
❌  Также переместить нужно в пакет, который предназначен для этого. В cmd только конфигурация и запуск приложения, вся логика должна быть структурирована по пакетам и типам

2023-10-31 13:25 UTC, capsulated commented on internal/dump/dump.go
> +package dump
👍 Отличная мысль, создать специальный воркер, причём с использованием сегрегированных интерфейсов. Только для логгера нужно нейминг интерфейса изменить, так как дублируется, и переименовать в что-то типа **ErrorLogger** и **InfoLogger**

2023-10-31 13:25 UTC, capsulated commented on internal/metrics/agent/agent.go
> +package agent
Агент - тоже хороший воркер получился 👍

2023-10-31 13:25 UTC, capsulated commented on internal/metrics/transports/http.go
> +func (h *HTTPSimpleTransport) Send(metric *report.MetricItem) error {
Это не совсем транспорт, конечно. Чуть чуть сбивает с толку, так как transport - это объект на уровне TCP/IP и выглядит он так: https://pkg.go.dev/net/http@go1.21.3#Transport

Нейминг, наверное, лучше чуть другой взять

2023-10-31 18:50 UTC, benderr commented on internal/metrics/transports/http.go
> +func (h *HTTPSimpleTransport) Send(metric *report.MetricItem) error {
Сделал UrlSender и JsonSender

2023-10-31 18:51 UTC, benderr commented on internal/dump/dump.go
> +package dump
done

2023-10-31 18:51 UTC, benderr commented on cmd/server/main.go
> +type metricDumpRepository struct {
переместил в dump

2023-10-31 18:51 UTC, benderr commented on cmd/server/main.go
> +func getWriterFunc(filePath string) func() (io.WriteCloser, error) {
Объеденил с пакетом filedump

2023-10-31 18:51 UTC, benderr commented on cmd/server/main.go
> +func getReaderFunc(filePath string) func() (io.ReadCloser, error) {
Сделал отдельный пакет filedump - поставщик io.ReadWriteCloser, хотелось сразу отделить его от пакета dump, чтобы dump умел писать не только в файл, но в любое хранилище которое поддерживает интерфейс ReadWriteCloser

2023-10-31 18:51 UTC, benderr commented on internal/validate/validate.go
> +func ParseCounter(memType, name, value string) (*storage.Metrics, error) {
Перенес

2023-10-31 18:52 UTC, benderr commented on cmd/config/serverconfig/main.go
>  import (
Перенес в отдельные пакеты в internal

2023-11-01 11:55 UTC, capsulated approved these changes
👍

2023-11-01 12:10 UTC, merged